/* Practice text. Lowercase, no punctuation; the first letter is capitalized at runtime. */
export const PANGRAMS: string[] = [
  "the quick brown fox jumps over the lazy dog",
  "pack my box with five dozen liquor jugs for Max",
  "sphinx of black quartz judge my vow",
  "how vexingly quick daft zebras jump in Oslo"
];

export const SENTENCES: string[] = [
  "please bring the blue jacket when you come over",
  "we could walk to the park after lunch today",
  "my phone battery died right before the meeting",
  "the coffee shop on the corner opens at seven",
  "she kept the old map folded in her pocket",
  "quiet mornings are perfect for a long run",
  "our team shipped the new feature last week",
  "the kids built a fort out of couch pillows",
  "just leave the keys on the kitchen counter",
  "a warm bowl of soup fixes almost everything",
  "we missed the last train and walked home",
  "he painted the fence a bright shade of yellow",
  "the puppy chased its tail for five minutes",
  "can you send me the photos from the trip",
  "the museum is free on the first weekend",
  "my plants are finally growing new leaves",
  "the pilot announced a short delay on the runway",
  "we should book the hotel before prices jump",
  "every good plan needs a backup plan",
  "the jazz band played until almost midnight",
  "quickly zip up your bag before it rains",
  "the squirrel buried an acorn under the oak",
  "pick up milk eggs and bread on the way home",
  "the lake was calm and quiet at dawn",
  "he fixed the squeaky door with a little oil",
  "we are going camping near the mountains",
  "the zoo keeper fed the hungry penguins",
  "she typed the whole report on her phone",
  "my brother makes the best pizza in town",
  "the storm knocked out power for an hour",
  "our neighbor plays piano every evening",
  "the library quietly extended its hours",
  "practice a little every day and you improve",
  "the waves crashed against the rocky shore",
  "please reply when you get a chance",
  "the recipe calls for two cups of flour",
  "a gentle breeze moved through the tall grass",
  "we watched the parade from the balcony",
  "the market sells fresh peaches all summer",
  "his joke made the whole room laugh",
  "the jury took three days to reach a verdict",
  "my calendar is packed with meetings today",
  "the bakery sold out of croissants by nine",
  "they found a quiet spot by the river",
  "the printer jammed again this morning",
  "a fox crept quietly past the sleeping dog",
  "we need a bigger box for the lamp",
  "the hikers reached the summit before noon",
  "keep your thumbs relaxed and light",
  "the movie was better than the book",
  "she knitted a cozy scarf for winter",
  "the pizza oven reached a blazing heat",
  "a flock of geese flew over the valley",
  "the new bridge opened to traffic today",
  "we played board games until very late",
  "the cat napped in a patch of sunlight",
  "he asked for extra pickles on the side",
  "our flight lands just after six tonight",
  "the old clock in the hallway stopped",
  "my sister is learning to play the violin",
  "the snow made the whole town look quiet",
  "bring a jacket because it gets cold at night",
  "the farmer planted long rows of pumpkins",
  "please double check the address before you go",
  "the podcast episode was about deep sea fish",
  "we split the bill and walked to the pier",
  "the lamp flickered and then went dark",
  "the kayak drifted slowly down the creek",
  "a quick nap can make the afternoon better",
  "the wizard waved his wand at the empty jar",
  "she organized the pantry by color",
  "the team huddled up before the final play",
  "my keyboard is covered in cookie crumbs",
  "the bus was packed with loud students",
  "the chef tasted the soup and added salt",
  "we ordered dumplings and spicy noodles",
  "the hotel pool was warm and empty",
  "the bike path follows the river for miles",
  "he whistled a happy tune on the porch",
  "the owl hooted from the top of the pine",
  "please grab two tickets for the late show",
  "a jar of honey sat on the windowsill",
  "the puzzle was missing just one piece",
  "they moved into a small house by the lake",
  "the email bounced back with an error",
  "our garden grew way too many zucchini",
  "the violin case was lined with velvet",
  "the explorer mapped a frozen river valley",
  "the box of old photos brought back memories",
  "quality over quantity is a good rule",
  "the jet left a white trail across the sky",
  "we paused the show to make popcorn",
  "the dog wagged its tail at the mail carrier",
  "my favorite mug has a chip on the handle",
  "the quiz had six questions about space",
  "he zipped his coat and stepped into the wind",
  "the lazy afternoon drifted by slowly",
  "we kept the windows open all night",
  "the kitten pounced on a piece of yarn",
  "please keep the volume low after ten",
  "a mix of jazz and blues filled the room",
  "she jogged past the quiet harbor",
  "the query returned zero rows again",
  "push the fix and merge the branch",
  "the build passed on the very first try",
  "never deploy right before a long weekend",
  "the toddler giggled at the bubbles",
  "we packed sandwiches for the long drive",
  "the vet said the puppy is perfectly healthy",
  "an equal number of apples and plums",
  "the joggers kept a steady pace uphill",
  "our waiter brought extra napkins and ketchup",
  "the sky turned pink just after sunset",
  "a big wave soaked everyone on the dock",
  "he keeps his spare keys in a blue box",
  "the knight quietly polished his helmet",
  "we exchanged gifts by the warm fireplace",
  "we flew to Denver and drove up to Boulder",
  "Maya and Leo met for coffee near the park",
  "I left my umbrella at the office again",
  "the train from Boston arrives around noon",
  "my cousin Priya just moved to Chicago",
  "we watched the game with Sam and Jordan",
  "I think Friday works better for the review",
  "the Pacific looked calm from the ferry",
  "Grandma Rose makes the best apple pie",
  "our trip to Tokyo starts in early April",
  "I asked Chris to bring the extra chairs",
  "the kids named the new puppy Biscuit",
  "we hiked Mount Rainier last August",
  "Zoe booked a table for six on Saturday",
  "I need to call Dr Patel before Monday",
  "the band played a late show in Oakland",
  "Ben and Quinn biked along the river in Paris",
  "I read that whole book on the flight to Dallas",
  "the rain in Seattle finally let up in July",
  "we met Kate and Owen at the market",
  "Nora quietly finished the puzzle before dinner",
  "Uncle Victor tells the same joke every year",
  "I promised Ellie we would visit Vermont",
  "Xavier moved from Madrid to Lisbon",
  "I sent the draft to Hannah and Yusuf",
  "we drove through Utah and into Nevada",
  "Iris keeps a tiny cactus named Spike",
  "the meeting with Anna moved to Tuesday",
  "Jake and I swapped desks on Wednesday",
"the kettle clicked off just as the toast popped",
"we left the umbrella in the back of the taxi",
"the neighbors are painting their porch bright blue",
"my coffee went cold while I answered emails",
"the storm rolled in faster than the forecast said",
"she found a quarter in the pocket of her jeans",
"the grocery line wrapped around the frozen aisle",
"he forgot his headphones on the morning bus",
"the dog refused to walk past the loud fountain",
"we split a slice of cake after the long hike",
"the elevator stopped on every single floor",
"please text me when your flight lands safely",
"the library printer only prints in black and white",
"a single goose honked at the joggers by the pond",
"the soup needs a pinch more salt and pepper",
"our tomatoes finally turned red this week",
"the tiny kitten hid behind the washing machine",
"my alarm went off twice before I got up",
"we should fix the squeaky hinge on the gate",
"the van was packed with boxes and plant pots",
"he whispered the answer so nobody else heard",
"the lemonade stand sold out before lunch",
"the baby giggled every time the dog sneezed",
"I tripped over my own shoelace on the stairs",
"the parking lot was nearly empty at dawn",
"she keeps a spare charger in her backpack",
"the pizza arrived hot and smelled amazing",
"we waited out the rain under a bus shelter",
"the clock in the kitchen runs five minutes fast",
"my brother always wins at card games",
"the jazz trio played softly by the window",
"the waiter brought extra lemon for the tea",
"our old car makes a funny noise when it turns",
"the museum shop sells postcards and puzzles",
"the kids built a snowman with a carrot nose",
"the fox slipped quietly under the garden fence",
"he juggled three oranges without dropping one",
"the cafe plays quiet music in the mornings",
"the market smelled like fresh bread and herbs",
"we took the long way home to see the lights",
"the zipper on my jacket keeps getting stuck",
"a quick nap made the drive much easier",
"the plumber fixed the leak in ten minutes",
"the hotel lobby had a huge vase of tulips",
"my sister borrowed my favorite gray sweater",
"the bus driver waved as we crossed the street",
"the kayak tipped over near the muddy bank",
"he keeps his keys on a hook by the door",
"the orchestra tuned up before the concert",
"we played frisbee until the sun went down",
"the dentist said to floss a little more often",
"the new bakery opens early on weekends",
"the thunder made the windows rattle a bit",
"she zipped up the tent before the rain started",
"the puppy chewed through a brand new slipper",
"the traffic light stayed red for ages",
"I left a sticky note on the fridge door",
"the stars were bright far away from the city",
"he mixed the paint until it turned light green",
"the cat knocked a pen off the desk again",
"we needed a ladder to reach the top shelf",
"the boat rocked gently in the quiet harbor",
"the teacher handed back the quiz on Friday",
"my phone buzzed during the quiet movie scene",
"the bread rose perfectly in the warm kitchen",
"the fireworks lit up the whole valley",
"the squirrel raced up the oak with a nut",
"she packed a jar of jam for the picnic",
"the garage smelled like oil and cut grass",
"we laughed so hard our faces hurt",
"the laptop fan whirred during the video call",
"the farmer sold us a box of juicy peaches",
"he lost his voice after cheering all night",
"the train was quiet except for one snoring man",
"the bike tire went flat halfway to work",
"the lake froze solid for the first time in years",
"my grandmother knits a scarf every winter",
"we lined up early for the concert tickets",
"the vending machine ate my last coin",
"the sunflowers grew taller than the fence",
"the chef flipped the pancake with one hand",
"the office plant needs more light and water",
"a gentle breeze carried the smell of rain",
"the tickets were cheaper on a weekday",
"he dropped his toast butter side down",
"the museum guard asked us to lower our voices",
"the fridge hums louder than it used to",
"we missed the exit and took the next one",
"the parrot repeated every word we said",
"she wore a bright yellow raincoat to school",
"the heater clicked on as the room cooled",
"the mail carrier left the box by the gate",
"the soccer match went into extra time",
"I baked cookies but burned the second tray",
"the moon looked huge over the dark hills",
"the kids chased bubbles across the lawn",
"the coffee shop ran out of oat milk",
"my shoes squeaked on the shiny gym floor",
"the carpet needs a good vacuum this week",
"he wrote a quick note and signed his name",
"the windows fogged up during the hot shower",
"the tour guide knew every hidden corner",
"we heard an owl hoot just after midnight",
"the bridge was closed for repairs all week",
"the box of crayons had every shade of blue",
"my sandwich got squashed in my bag",
"the stadium lights came on at dusk",
"she jumped over the puddle and still got wet",
"the orange cat sleeps on top of the fridge",
"the waves washed away our sandcastle",
"the printer jammed on the very last page",
"we found a quiet table in the back corner",
"the pizza dough needs to rest for an hour",
"the bus was late so we walked instead",
"he adjusted his glasses and kept reading",
"the garden hose sprang a small leak",
"my phone battery dropped to five percent",
"the tea kettle whistled from the stove",
"the zoo had a new baby giraffe",
"we grabbed a quick lunch between meetings",
"the ice cream melted down my wrist",
"a big truck blocked the whole driveway",
"the baker dusted the loaves with flour",
"she answered the phone on the first ring",
"the puzzle had a thousand tiny pieces",
"the lawn mower roared next door all morning",
"my socks never seem to match anymore",
"the soup simmered slowly on low heat",
"we kept the windows open for the breeze",
"the jet flew low over the beach",
"he asked for the check and a box for leftovers",
"the vet gave the dog a small treat",
"the library book was due last Tuesday",
"our team won the trivia night by one point",
"the candle flickered in the drafty room",
"the cyclists waved as they zoomed past",
"I forgot where I parked the car again",
"the hikers stopped to fill their water bottles",
"the old barn leaned a little to the left",
"she kept a journal by the side of her bed",
"the fog lifted by the middle of the morning",
"the seagulls fought over a dropped fry",
"we painted the fence a soft shade of gray",
"the washing machine beeped three times",
"he hung the picture slightly crooked",
"the market was crowded on Saturday morning",
"the pancakes were fluffy and golden brown",
"the phone screen cracked in the corner",
"the violin teacher tapped out the rhythm",
"the rain boots stood by the back door",
"we toasted marshmallows over the fire",
"the quiet street was lined with maple trees",
"my cousin sends the funniest videos",
"the chocolate cake disappeared in minutes",
"the bus stop has a new glass shelter",
"the kids made a fort out of blankets",
"the waiter recommended the fish of the day",
"the hallway light flickers now and then",
"she jogged three laps around the park",
"the thermostat was set a bit too high",
"we rode the ferry across the calm bay",
"the backpack zipper finally broke",
"he shared his umbrella with a stranger",
"the peaches were ripe and very sweet",
"the dog wagged its whole body at the door",
"the bakery smelled like cinnamon and sugar",
"my plant grew a new leaf overnight",
"the concert ended with a quiet encore",
"the kitchen timer went off too early",
"we watched the sunset from the rooftop",
"the wind blew the hat right off his head",
"the cashier counted the change twice",
"the jigsaw puzzle is missing a corner piece",
"she ordered extra pickles on her burger",
"the rowboat drifted toward the reeds",
"our flight was delayed by a few hours",
"the grass was wet with morning dew",
"he always hums while he cooks dinner",
"the power went out during the storm",
"the goldfish swam in slow little circles",
"my alarm clock needs a new battery",
"the ice rink was packed on the holiday",
"we carried the couch up three flights of stairs",
"the frog jumped into the pond with a splash",
"she waved from the top of the ferris wheel",
"the lettuce from the garden was crisp",
"the cold wind made our noses turn red",
"the tacos were spicy but really good",
"the soccer ball rolled into the street",
"my keyboard has a sticky space bar",
"the calm lake reflected the snowy peaks",
"he fixed the wobbly table with a folded napkin",
"the choir sang an old folk song",
"the kitten batted at a piece of string",
"we swapped books at the little free library",
"the oven took forever to heat up",
"the mountain trail was steep and rocky",
"she tucked a note inside the lunch box",
"the kids raced to the end of the dock",
"the milk carton was almost empty",
"the band loaded their gear into a van",
"a lazy cat stretched across the doormat",
"we planted bulbs that bloom in spring",
"the streetlights hummed on the empty block",
"he packed his bag the night before",
"the maple syrup dripped onto the plate",
"my friend taught me a new card trick",
"the heavy rain flooded the side street",
"the smell of popcorn filled the theater",
"she fixed her bike with a small wrench",
"the geese flew south in a long line",
"the waiter spilled water on the menu",
"our tent leaked during the night",
"the tiny shop sold handmade soap",
"he locked the door and checked it twice",
"the baby fell asleep in the car seat",
"the fireplace crackled all evening",
"we raked the leaves into a huge pile",
"the jazz album sounds better on vinyl",
"my knees hurt after the long run",
"the moving truck arrived an hour early",
"the kids squealed at the petting zoo",
"the salad needs a little more dressing",
"she read the whole book in one day",
"the city bus smelled like wet umbrellas",
"the cherry tree blossomed overnight",
"we practiced parallel parking in the lot",
"the quiz show host told bad jokes",
"the dog snored loudly by the heater",
"he wrapped the gift in brown paper",
"the ferry horn echoed across the water",
"my glasses fogged up in the cold",
"the paint dried faster than we expected",
"the fruit bowl was full of ripe plums",
"she keeps her plants on the window sill",
"the shopping cart had a wobbly wheel",
"we sang along to every song on the radio",
"the bicycle bell rang twice behind us",
"the cake tasted better the next day",
"the hikers spotted a deer by the creek",
"he sharpened every pencil in the drawer",
"the drizzle turned into a heavy downpour",
"my new shoes gave me a blister",
"the chef tossed the noodles in a hot pan",
"the beach was quiet in the early morning",
"we got lost in the maze of tall corn",
"the lamp by the couch needs a new bulb",
"she mailed the package on her way home",
"the old piano was slightly out of tune",
"the traffic cleared up after the bridge",
"our cat hates the sound of the blender",
"he checked the weather before the trip",
"the rain made the cobblestones shiny",
"the kids pressed flowers in a thick book",
"my water bottle leaked in my bag",
"the waves sparkled in the afternoon sun",
"we ordered too much food for two people",
"the sheep crowded around the farmer",
"the elevator music was oddly relaxing",
"she painted her nails a deep shade of red",
"the hot chocolate warmed our cold hands",
"the student raised her hand to ask a question",
"he found an old coin in the sand",
"the leaves crunched under our boots",
"my calendar is full of dentist visits",
"the fox cub peeked out from the bushes",
"we built a birdhouse from scrap wood",
"the soup kitchen needed extra volunteers",
"the thunderstorm knocked over a small tree",
"she cut the sandwich into neat triangles",
"the new glasses made everything look sharp",
"the orange juice was freshly squeezed",
"we dozed off on the sunny porch",
"the long queue moved surprisingly fast",
"my friend Zara just adopted a puppy",
"we visited Quebec during the snowy winter",
"Jack and Olivia fixed the kitchen sink",
"I met Kevin at the zoo on Sunday",
"the parade through Boston started at noon",
"Uncle Max makes pancakes every Saturday",
"we drove from Denver to Santa Fe in a day",
"Maya forgot her keys at the office again",
"the flight to Zurich was quiet and smooth",
"I asked Jordan to water the plants in June",
"Grandpa Joe still fixes his own bike",
"we spent a week in Vancouver last fall",
"Priya and Sam are hosting dinner Friday",
"the museum in Oslo had a Viking ship",
"I promised Quinn we would visit New York",
"Leo baked a lemon cake for Hannah",
"the market in Madrid opens very early",
"my neighbor Victor grows huge pumpkins",
"we watched the game at Kate and Owens place",
"I will call Dr Kim about the checkup",
"Zoe and Jake walked their dogs in the park",
"the train to Chicago left right on time",
"Aunt Rosa sent a postcard from Mexico",
"I think Tuesday works for the dentist",
"the jazz club in New Orleans was packed",
"Ellie wants to learn French this year",
"we took the kids to the lake in July",
"Marcus left his jacket at the gym",
"the ferry to Victoria was a bit choppy",
"I bought Nora a book for her birthday",
"Kai and Luna built a treehouse together",
"we flew into Phoenix late on Monday night",
"my coworker Felix drinks way too much coffee",
"the pizza place in Brooklyn closes at ten",
"I told Iris about the new bakery downtown",
"Xander fixed the printer on the third try",
"we hiked in Yosemite for three days",
"Mom mailed a box of cookies to Seattle",
"Jasmine won the spelling bee in April",
"the bookstore in Portland has a cozy cat",
"I owe Ben a coffee for helping me move",
"we met Tessa and Raj at the airport",
"Coach Rivera made us run extra laps",
"the snow in Minnesota lasted until March",
"Theo plays the violin every evening",
"I lent my bike to Grace for the weekend",
"we ate dumplings in Vancouver with Mei",
"Captain Ortiz announced a smooth landing",
"Lucy found a quiet spot to read in Berlin",
"my brother Jonah moved to Atlanta",
"the Olympics were on every channel in August",
"I asked Amir to bring the extra chairs",
"Rosie the dog sleeps on the kitchen rug",
"we rented a small cabin near Lake Tahoe",
"Dad fixed the fence before Thanksgiving",
"Hugo taught me how to make tacos",
"the concert in Austin sold out quickly",
"I sent Wendy the photos from the wedding",
"Oscar keeps a tiny cactus on his desk",
"we celebrated New Year in Sydney",
"Kim and Jess painted the spare room yellow",
"the bakery in Paris sold warm croissants",
"I finally finished the puzzle Zack gave me",
"Mrs Lopez grows tomatoes on her balcony",
"we waited for Ivy at the train station",
"Noah juggled at the talent show in May",
"the book club meets every other Thursday",
"I texted Quincy about the pizza order",
"Sofia and Ravi went hiking in Colorado",
"we drove through Vermont to see the leaves",
"Omar forgot his umbrella in London",
"my cousin Beatrix knits cozy hats",
"the coffee in Rome was small but strong",
"I asked Yuki where she got her jacket",
"we watched fireworks over the Hudson",
"Peter fixed the squeaky door on Sunday",
"the zoo in San Diego has pandas",
"I will meet Ava at the library at noon",
"Maxine hiked the whole trail in a week",
"we sent a gift basket to the Johnsons",
"Frank and Vera celebrated fifty years",
"the quiz on Wednesday covers chapter six",
"the quick cyclist zipped past the bus",
"six jumbo boxes of fizzy juice went missing",
"the jazz quartet played a lively tune",
"a lazy zebra dozed beside the quiet river",
"we mixed frozen berries into the yogurt",
"the jolly baker glazed a dozen donuts",
"the wizard hid his prized quill in a box",
"quick jabs of the brush fixed the wall",
"the vixen quickly crept past the kennel",
"a dozen quail waddled across the road",
"she squeezed the lemons for the vinaigrette",
"the jukebox played an old waltz",
"the jogger quickly zigzagged through the crowd",
"he boxed up the jigsaw puzzle with care",
"the quirky zoo keeper fed the lazy yak",
"my pajamas have tiny foxes on them",
"the queen quietly vexed the jesters",
"we kayaked past a quaint fishing village",
"the jumbo jet taxied toward the runway",
"he waxed the vintage van until it shone",
"the buzzing fridge kept me awake",
"six quick jumps and the kids were done",
"the fuzzy kiwi fruit sat in a bowl",
"a vivid zigzag of lightning split the sky",
"the jazz fest drew a huge crowd",
"she sketched a quick map of the maze",
"the frozen yogurt shop has kiwi flavor",
"we quizzed each other before the exam",
"the boxer jumped rope for ten minutes",
"the velvet jacket was a lucky find",
"the grizzly bear sniffed the empty cooler",
"a quiet breeze swayed the tall oaks",
"he fixed the jammed zipper with pliers",
"the quilt was sewn from vivid squares",
"the waxy leaves glowed after the rain",
"my buzzing phone woke the sleeping baby",
"the jovial chef juggled six eggs",
"a dozen oxen pulled the heavy wagon",
"the quick brown squirrel darted away",
"he queued for the vending machine",
"the zany clown squeezed into a tiny car",
"a kayak zipped across the quiet bay",
"the judge quickly quieted the room",
"the bakery boxes were stacked in a van",
"my jacket pocket held a squished muffin",
"the extra fizzy soda sprayed everywhere",
"we joked about the quirky wax statues",
"the jaguar prowled quietly in the zoo",
"the mixer whirred as she made the batter",
"the jagged cliffs overlooked the sea",
"he quickly jotted down the phone number",
"the frozen lake squeaked under our skates",
"six vivid kites zipped over the beach",
"the quiz master asked a tricky question",
"the toxic smoke made everyone move away",
"the jewelry box had a tiny broken lock",
"we zipped the tent against the chilly wind",
"the vet examined the jumpy puppy",
"a hazy glow hung over the quiet town",
"the jackrabbit zigzagged across the field",
"the explorer packed a compass and a map",
"she quickly fixed the wobbly chair leg",
"the crazy storm knocked out the power",
"the jelly jar was stuck and would not open",
"he waxed his skis before the trip",
"the quaint inn served warm apple juice",
"the buzzer sounded at the end of the game",
"we found a jade necklace at the flea market",
"the lynx vanished into the snowy woods",
"my zucchini bread came out a bit dry",
"the textbook weighed as much as a brick",
"the kids quickly tidied up the playroom",
"the jittery kitten jumped at every noise",
"a quick fox jumps over the sleepy hound",
"she plays the xylophone in the school band",
"the job fair was packed with students",
"we squeezed into the back of the taxi",
"the boxer puppy chewed the yellow rope",
"the chilly breeze made us zip our coats",
"the vivid mural covered the whole wall",
"he joined the jazz band last semester",
"the quiet cove was perfect for a swim",
"the dizzy toddler spun until she fell over",
"a flock of quick swallows skimmed the lake",
"we waxed the old oak table on Sunday",
"the pizza oven blazed in the backyard",
"the joyful crowd cheered for the runners",
"my backpack is heavy with library books",
"the grumpy judge frowned at the lawyer",
"a mix of jazz and blues drifted outside",
"the frozen peas thawed on the counter",
"the jogger paused to tie her shoe",
"he squinted at the tiny print on the box",
"the fizzy drink went flat by noon",
"we saw a huge moose by the lake",
"the extra blanket kept the puppy warm",
"the quirky museum had a room of clocks",
"a vivid sunset glowed behind the hills",
"she zipped her suitcase and called a cab",
"the jumpy squirrel froze on the fence",
"the kiosk sold maps and bottled water",
"we quickly jotted notes during the talk",
"the wax candle dripped onto the table",
"a lazy afternoon drifted by slowly",
"the brisk walk woke us up",
"the violinist bowed and the crowd cheered",
"the teapot squeaked as it heated up",
"my jeans got muddy at the pumpkin patch",
"the quiet library was a perfect escape",
"the kids jumped in the pile of leaves",
"he fixed the leaky faucet with a new washer",
"the fuzzy peaches were soft and sweet",
"we packed six jars of homemade jam",
"the fox kits played near their den",
"a gentle drizzle fell on the zinc roof",
"the knight polished his shield and sword",
"she mixed the dough with her bare hands",
"the jury listened to every word",
"the crowded bazaar sold spices and rugs",
"my dizzy dog chased its tail again",
"the zipper pouch held all my pens",
"we watched a jazz show on the pier",
"the bright blue kayak rested on the dock",
"he quickly squashed the buzzing fly",
"the vintage jukebox still works",
"the frosty grass crunched under our feet",
"the jolly mail carrier whistled as he walked",
"a dozen jars of pickles lined the shelf",
"the quick shower helped after the hike",
"we vowed to wake up early for the sunrise",
"the plaza fountain sparkled in the sun",
"my jacket zipper snagged on the lining",
"the kids quizzed their dad on state capitals",
"the oxygen mask dropped during the drill",
"she jotted a grocery list on her hand",
"the luxury hotel had a rooftop pool",
"a quiet hush fell over the crowd",
"the lazy river looped around the park",
"the jeweler fixed the clasp on my watch",
"we explored a cave full of glowing worms",
"the boxes of books were heavy to lift",
"he quickly zipped his lips and smiled",
"the zebra finch sang from its little cage",
"a squeaky wheel gets fixed first",
"the quiet waiter refilled our water",
"my jumbo mug holds three cups of tea",
"we ate frozen grapes on the hot porch",
"the vivid colors faded in the wash",
"the jackhammer woke the whole block",
"she wrapped the gift with a velvet bow",
"the kind stranger held the door open",
"a quick thank you note goes a long way",
"the extra pillow made the couch cozy",
"we spotted a fox on the way to work",
"the big blue whale surfaced near the boat",
"he mixed the salad with a wooden spoon",
"the quilted blanket kept us warm",
"the busy airport was calm at midnight",
"my goofy dog sneezes when he is excited",
"the dozen roses lasted almost a week",
"we zigzagged up the steep mountain path",
"the sly fox snuck into the hen house",
"a jar of honey sat by the teapot",
"the hazy morning turned into a bright day",
"she squeezed past the crowd to the front",
"the jumbo pretzel was bigger than my head",
"he kept a spare key under the doormat",
"the vivid dream felt completely real",
"the quick breakfast kept us going till noon",
"we waxed the surfboards before the swim",
"the kitchen smelled like fresh basil",
"my pen ran out of ink during the exam",
"the jolly fisherman told us tall tales",
"a frozen puddle cracked under my boot",
"the young owl blinked at the flashlight",
"she jogged past the quiet cemetery",
"the boxy car fit in the tiny spot",
"the wheat field swayed in the warm wind",
"we joked around while we did the dishes",
"the quick storm passed within the hour",
"he squinted into the bright afternoon sun",
"the fox and the hound became unlikely friends",
"the jam session lasted late into the night",
"my tiny apartment has a huge window",
"the kids made lemonade to sell on the corner",
"we zipped down the hill on our sleds",
"a crazy idea turned into a great plan",
"the velvet curtain rose on the second act",
"the quiet town woke up to fresh snow",
"she fixed the squeaky wheel with some oil",
"the jumbo shrimp were grilled with garlic",
"he checked the map and turned left",
"the brave kid jumped off the high board",
"a zebra crossing was painted outside school",
"the soup was too hot so we waited",
"my aunt makes the best apple pie",
"the quiet kayak glided over the water",
"we sang happy birthday a little off key",
"the jagged rocks made the climb tricky",
"she wore her lucky socks to the exam",
"the fuzzy caterpillar crawled up my arm",
"a sudden gust of wind flipped my umbrella",
"the backyard grill smelled like summer",
"he taught his daughter to ride a bike",
"the quilt shop had fabric in every color",
"we explored the old fort by the harbor",
"the lazy dog barely lifted its head",
"my phone slipped into the couch cushions",
"the vivid purple flowers attracted bees",
"a quick jog cleared my head",
"the boxes were labeled kitchen and bath",
"she zipped through the crossword in minutes",
"the jazz pianist closed her eyes and played",
"we woke up to the smell of pancakes",
"the frozen river cracked in the spring sun",
"he placed the vase gently on the table",
"the quiet hum of the fridge filled the room",
"a jumble of shoes piled up by the door",
"the young fox hunted mice in the snow",
"my squeaky shoes announced my arrival",
"we took turns pushing the stroller uphill",
"the cozy cabin had a wood stove",
"she jumped when the toaster popped",
"the quick lunch break turned into a long chat",
"a bunch of kids waited for the ice cream truck",
"the vase of daisies brightened the room",
"he quietly closed the door behind him",
"the jagged mountain peaks glowed pink at dawn",
"we mixed blue and yellow to make green",
"the dizzy heat made us stay inside",
"my bike chain slipped off on the hill",
"the old fax machine still sat in the corner",
"she quickly packed a bag for the weekend",
"the jug of iced tea was gone by noon",
"a pack of wolves howled in the distance",
"the zoo keeper waved to the excited kids",
"we lounged by the pool all afternoon",
"the warm soup was just what we needed",
"he joked that the cake was a work of art",
"the quiet valley echoed with birdsong",
"my best friend lives just down the block",
"the kids built a volcano for the science fair",
"she kept the receipt just in case",
"the huge oak shaded the whole backyard",
"a small boat bobbed near the pier",
"we quickly realized we took the wrong bus",
"the vivid green moss covered the rocks",
"he folded the map the wrong way again",
"the jumpy frog escaped from the bucket",
"my tea steeped too long and turned bitter",
"the cozy blanket fort took all afternoon",
"she swapped her heels for comfy sneakers",
"the quiz had one very tricky question",
"a big wave soaked our towels and books",
"the fox tracks led into the snowy woods",
"we played a quick game of checkers",
"he zipped the cooler and grabbed the chairs",
"the jolly crowd sang along to the band",
"my knees shook during the job interview",
"the violets bloomed along the shady path",
"a lazy cloud drifted across the moon",
"the extra cheese made the pizza perfect",
"we fixed the broken kite with some tape",
"she jogged to the corner store for milk",
"the quiet morning was perfect for reading",
"the jet lag hit hard on the second day",
"he kept a jar of coins for a rainy day",
"the buzzing bees circled the lavender",
"my cousin juggles at birthday parties",
"we took a quick photo before the rain",
"the zebras grazed quietly on the plain",
"a frozen pizza saved our dinner plans",
"the velvet chair was surprisingly comfy",
"she quickly waved and hopped on the train",
"the jagged glass was swept up carefully",
"we visited the quirky shop on Main Street",
"the fog horn boomed across the bay",
"he asked for extra ice in his drink",
"the kind nurse brought an extra blanket",
"my puzzle box has a secret drawer",
"the quick sketch turned into a painting",
"a jar of pickles cracked on the floor",
"we watched the ducks glide across the pond",
"the vivid banners fluttered in the wind",
"she zipped around the rink on new skates",
"the job took longer than we planned",
"the huge pumpkin barely fit in the wagon",
"he quietly hummed a jazz tune",
"the lazy Sunday started with waffles",
"my water glass left a ring on the table",
"we joked about the terrible weather",
"the extra hour of sleep felt amazing",
"the fox yelped somewhere in the dark",
"a dozen balloons floated up to the ceiling",
"she squeezed the tube to get the last bit",
"the quiet cafe had the best window seat",
"we packed the car and hit the road early"
];

export const WORDS: string[] = ("about above across act add after again against age ago agree air all allow almost alone along already also always among amount and animal another answer any appear apple area arm army around art ask away baby back bad bag ball bank bar base basket be bear beat beauty bed been before begin behind being believe below best better between big bike bird bit black blank block blood blow blue board boat body bone book born both bottom box boy bread break bright bring broad brother brown build busy but buy by cake call calm camp can capital car card care carry case cat catch cause cell center chair chance change check chief child choose circle city class clean clear climb clock close cloud coast coat cold color come common copy corn corner cost could count country course cover cozy crowd cry cup cut dance dark day deal dear decide deep desk detail did die dinner direct do doctor dog dollar done door double down draw dream dress drink drive drop dry duck during each early earth east easy eat edge egg eight either else empty end enjoy enough enter equal even evening event ever every exact example except excite exercise expect expert explain extra eye face fact fair fall family famous far farm fast fat father favor fear feel feet few field fight figure fill final find fine finger finish fire first fish fit five fix flat floor flow flower fly follow food foot for force forest form forward four fox free fresh friend from front fruit full fun game garden gather gave gentle get gift give glad glass go gold gone good got grass gray great green ground group grow guess guide gum habit hair half hall hand happen happy hard has hat have he head hear heart heat heavy held help her here high hill him his hit hold hole home hope horse hot hour house how huge human hunt hurry ice idea if inch into invent iron island it item jacket jam jar jazz jeans jelly jet job jog join joke journey joy judge juice jump jungle junk just keen keep kept kettle key kick kid kind king kiss kit kitchen kite knee knew knife knit knock know lady lake land large last late laugh law lay lazy lead learn least leave left leg lemon length less let letter level lie life lift light like line lion list listen little live lock long look lose lot loud love low lucky lunch made magic main major make man many map mark market master match maybe meal mean meat meet melt member mind minute mirror miss mix model moment money month moon more morning most mother move much music must my name near neck need never new next nice night nine noise noon north nose note nothing notice now number object ocean off offer office often oil old on once one only open or order other our out over own oxygen page paint pair paper park part party pass past path pay peace pen people pepper pick picture piece pilot pink pipe pizza place plain plan plant play please plenty pocket point polite pool poor pop power press pretty print prize problem proof proud pull pump puppy purple push put puzzle quack quality quart queen query quest question quick quiet quilt quite quiz quote race radio rain raise ran rather reach read ready real reason record red remember reply rest rich ride right ring rise river road rock roll room root rope rose round row rule run safe said sail salt same sand save saw say scale school science score sea seat second see seed seem sell send sense seven shape share sharp she shell shine ship shoe shop short should show side sight sign silent silver simple since sing sister sit six size skill skip sky sleep slip slow small smell smile snow so soft soil some song soon sound soup south space speak special speed spell spend spot spring square stand star start stay steady step stick still stone stop store story strange street strong study such sugar summer sun supply sure swim table tail take talk tall taste teach team tell ten test than thank that the their them then there these they thick thin thing think third this those though three through throw tie time tiny tip today together told tomorrow tone too took top touch toward town toy track trade train travel tree trip true try turn twelve twenty two type under unit until up upon us use usual valley value van vast very view village violin visit vivid voice volume vote wagon wait walk wall want warm was wash watch water wave way we wear weather week weigh well went were west what wheel when where which while white who whole why wide wife wild will win wind window wing winter wire wise wish with woman wonder wood word work world worry would write wrong yard year yell yellow yes yet you young your youth zany zap zebra zero zest zigzag zinc zip zone zoo zoom").split(" ");
