/* Practice text. Lowercase, no punctuation; the first letter is capitalized at runtime. */
export const PANGRAMS: string[] = [
  "the quick brown fox jumps over the lazy dog",
  "pack my box with five dozen liquor jugs for Max",
  "sphinx of black quartz judge my vow",
  "how vexingly quick daft zebras jump in Oslo"
];

export const SENTENCES: string[] = [
  "please bring the blue jacket when you come over",
  "we could walk to the park after lunch today",
  "my phone battery died right before the meeting",
  "the coffee shop on the corner opens at seven",
  "she kept the old map folded in her pocket",
  "quiet mornings are perfect for a long run",
  "our team shipped the new feature last week",
  "the kids built a fort out of couch pillows",
  "just leave the keys on the kitchen counter",
  "a warm bowl of soup fixes almost everything",
  "we missed the last train and walked home",
  "he painted the fence a bright shade of yellow",
  "the puppy chased its tail for five minutes",
  "can you send me the photos from the trip",
  "the museum is free on the first weekend",
  "my plants are finally growing new leaves",
  "the pilot announced a short delay on the runway",
  "we should book the hotel before prices jump",
  "every good plan needs a backup plan",
  "the jazz band played until almost midnight",
  "quickly zip up your bag before it rains",
  "the squirrel buried an acorn under the oak",
  "pick up milk eggs and bread on the way home",
  "the lake was calm and quiet at dawn",
  "he fixed the squeaky door with a little oil",
  "we are going camping near the mountains",
  "the zoo keeper fed the hungry penguins",
  "she typed the whole report on her phone",
  "my brother makes the best pizza in town",
  "the storm knocked out power for an hour",
  "our neighbor plays piano every evening",
  "the library quietly extended its hours",
  "practice a little every day and you improve",
  "the waves crashed against the rocky shore",
  "please reply when you get a chance",
  "the recipe calls for two cups of flour",
  "a gentle breeze moved through the tall grass",
  "we watched the parade from the balcony",
  "the market sells fresh peaches all summer",
  "his joke made the whole room laugh",
  "the jury took three days to reach a verdict",
  "my calendar is packed with meetings today",
  "the bakery sold out of croissants by nine",
  "they found a quiet spot by the river",
  "the printer jammed again this morning",
  "a fox crept quietly past the sleeping dog",
  "we need a bigger box for the lamp",
  "the hikers reached the summit before noon",
  "keep your thumbs relaxed and light",
  "the movie was better than the book",
  "she knitted a cozy scarf for winter",
  "the pizza oven reached a blazing heat",
  "a flock of geese flew over the valley",
  "the new bridge opened to traffic today",
  "we played board games until very late",
  "the cat napped in a patch of sunlight",
  "he asked for extra pickles on the side",
  "our flight lands just after six tonight",
  "the old clock in the hallway stopped",
  "my sister is learning to play the violin",
  "the snow made the whole town look quiet",
  "bring a jacket because it gets cold at night",
  "the farmer planted long rows of pumpkins",
  "please double check the address before you go",
  "the podcast episode was about deep sea fish",
  "we split the bill and walked to the pier",
  "the lamp flickered and then went dark",
  "the kayak drifted slowly down the creek",
  "a quick nap can make the afternoon better",
  "the wizard waved his wand at the empty jar",
  "she organized the pantry by color",
  "the team huddled up before the final play",
  "my keyboard is covered in cookie crumbs",
  "the bus was packed with loud students",
  "the chef tasted the soup and added salt",
  "we ordered dumplings and spicy noodles",
  "the hotel pool was warm and empty",
  "the bike path follows the river for miles",
  "he whistled a happy tune on the porch",
  "the owl hooted from the top of the pine",
  "please grab two tickets for the late show",
  "a jar of honey sat on the windowsill",
  "the puzzle was missing just one piece",
  "they moved into a small house by the lake",
  "the email bounced back with an error",
  "our garden grew way too many zucchini",
  "the violin case was lined with velvet",
  "the explorer mapped a frozen river valley",
  "the box of old photos brought back memories",
  "quality over quantity is a good rule",
  "the jet left a white trail across the sky",
  "we paused the show to make popcorn",
  "the dog wagged its tail at the mail carrier",
  "my favorite mug has a chip on the handle",
  "the quiz had six questions about space",
  "he zipped his coat and stepped into the wind",
  "the lazy afternoon drifted by slowly",
  "we kept the windows open all night",
  "the kitten pounced on a piece of yarn",
  "please keep the volume low after ten",
  "a mix of jazz and blues filled the room",
  "she jogged past the quiet harbor",
  "the query returned zero rows again",
  "push the fix and merge the branch",
  "the build passed on the very first try",
  "never deploy right before a long weekend",
  "the toddler giggled at the bubbles",
  "we packed sandwiches for the long drive",
  "the vet said the puppy is perfectly healthy",
  "an equal number of apples and plums",
  "the joggers kept a steady pace uphill",
  "our waiter brought extra napkins and ketchup",
  "the sky turned pink just after sunset",
  "a big wave soaked everyone on the dock",
  "he keeps his spare keys in a blue box",
  "the knight quietly polished his helmet",
  "we exchanged gifts by the warm fireplace",
  "we flew to Denver and drove up to Boulder",
  "Maya and Leo met for coffee near the park",
  "I left my umbrella at the office again",
  "the train from Boston arrives around noon",
  "my cousin Priya just moved to Chicago",
  "we watched the game with Sam and Jordan",
  "I think Friday works better for the review",
  "the Pacific looked calm from the ferry",
  "Grandma Rose makes the best apple pie",
  "our trip to Tokyo starts in early April",
  "I asked Chris to bring the extra chairs",
  "the kids named the new puppy Biscuit",
  "we hiked Mount Rainier last August",
  "Zoe booked a table for six on Saturday",
  "I need to call Dr Patel before Monday",
  "the band played a late show in Oakland",
  "Ben and Quinn biked along the river in Paris",
  "I read that whole book on the flight to Dallas",
  "the rain in Seattle finally let up in July",
  "we met Kate and Owen at the market",
  "Nora quietly finished the puzzle before dinner",
  "Uncle Victor tells the same joke every year",
  "I promised Ellie we would visit Vermont",
  "Xavier moved from Madrid to Lisbon",
  "I sent the draft to Hannah and Yusuf",
  "we drove through Utah and into Nevada",
  "Iris keeps a tiny cactus named Spike",
  "the meeting with Anna moved to Tuesday",
  "Jake and I swapped desks on Wednesday"
];

export const WORDS: string[] = ("about above across act add after again against age ago agree air all allow almost alone along already also always among amount and animal another answer any appear apple area arm army around art ask away baby back bad bag ball bank bar base basket be bear beat beauty bed been before begin behind being believe below best better between big bike bird bit black blank block blood blow blue board boat body bone book born both bottom box boy bread break bright bring broad brother brown build busy but buy by cake call calm camp can capital car card care carry case cat catch cause cell center chair chance change check chief child choose circle city class clean clear climb clock close cloud coast coat cold color come common copy corn corner cost could count country course cover cozy crowd cry cup cut dance dark day deal dear decide deep desk detail did die dinner direct do doctor dog dollar done door double down draw dream dress drink drive drop dry duck during each early earth east easy eat edge egg eight either else empty end enjoy enough enter equal even evening event ever every exact example except excite exercise expect expert explain extra eye face fact fair fall family famous far farm fast fat father favor fear feel feet few field fight figure fill final find fine finger finish fire first fish fit five fix flat floor flow flower fly follow food foot for force forest form forward four fox free fresh friend from front fruit full fun game garden gather gave gentle get gift give glad glass go gold gone good got grass gray great green ground group grow guess guide gum habit hair half hall hand happen happy hard has hat have he head hear heart heat heavy held help her here high hill him his hit hold hole home hope horse hot hour house how huge human hunt hurry ice idea if inch into invent iron island it item jacket jam jar jazz jeans jelly jet job jog join joke journey joy judge juice jump jungle junk just keen keep kept kettle key kick kid kind king kiss kit kitchen kite knee knew knife knit knock know lady lake land large last late laugh law lay lazy lead learn least leave left leg lemon length less let letter level lie life lift light like line lion list listen little live lock long look lose lot loud love low lucky lunch made magic main major make man many map mark market master match maybe meal mean meat meet melt member mind minute mirror miss mix model moment money month moon more morning most mother move much music must my name near neck need never new next nice night nine noise noon north nose note nothing notice now number object ocean off offer office often oil old on once one only open or order other our out over own oxygen page paint pair paper park part party pass past path pay peace pen people pepper pick picture piece pilot pink pipe pizza place plain plan plant play please plenty pocket point polite pool poor pop power press pretty print prize problem proof proud pull pump puppy purple push put puzzle quack quality quart queen query quest question quick quiet quilt quite quiz quote race radio rain raise ran rather reach read ready real reason record red remember reply rest rich ride right ring rise river road rock roll room root rope rose round row rule run safe said sail salt same sand save saw say scale school science score sea seat second see seed seem sell send sense seven shape share sharp she shell shine ship shoe shop short should show side sight sign silent silver simple since sing sister sit six size skill skip sky sleep slip slow small smell smile snow so soft soil some song soon sound soup south space speak special speed spell spend spot spring square stand star start stay steady step stick still stone stop store story strange street strong study such sugar summer sun supply sure swim table tail take talk tall taste teach team tell ten test than thank that the their them then there these they thick thin thing think third this those though three through throw tie time tiny tip today together told tomorrow tone too took top touch toward town toy track trade train travel tree trip true try turn twelve twenty two type under unit until up upon us use usual valley value van vast very view village violin visit vivid voice volume vote wagon wait walk wall want warm was wash watch water wave way we wear weather week weigh well went were west what wheel when where which while white who whole why wide wife wild will win wind window wing winter wire wise wish with woman wonder wood word work world worry would write wrong yard year yell yellow yes yet you young your youth zany zap zebra zero zest zigzag zinc zip zone zoo zoom").split(" ");
